import { a } from '@aws-amplify/backend';

export const Model = a.model({
    id: a.id().required(),
    idSublinea: a.string(),
    name: a.string(),
    slug: a.string(),
    modelsByYear: a.hasMany('ModelByYear', 'modelId'),
    vehicleId: a.id(),
    vehicle: a.belongsTo('Vehicle', 'vehicleId'),
    ModelAttrib: a.hasMany('ModelAttrib', 'modelId'),
    documentsByModel: a.hasMany('DocumentByModel', 'modelId'),
    categoryId: a.id(),
    // categories: a.hasMany('Category', 'modelId'),
    modelCategories: a.hasMany('ModelCategory', 'modelId'),
    vehicleSlug: a.string(),
    vehicleVersionName: a.string(),
    isMainVehicle: a.boolean().default(false),
    // Foreign key to the slider
    sliderId: a.id(),
    slider: a.belongsTo('DetailPageSlider', 'sliderId'),
    thirdPartyApiDataId: a.string(),
    vehicleFuelType: a.string(),
    posterImageMobile: a.string(),
    posterImageDesktop: a.string(),
    quotesMainImage: a.string(),
    quotesDescription: a.string(),
    isVehicleShownOnHomePage: a.boolean().default(false),
    isActive: a.boolean().default(true),
    bannerBackgroundColor: a.string(),
    objectPosition: a.string(),
    detailPageLink: a.string(),
    modelName: a.string(),
    cotizarLink: a.string(),
    detailPageMainBannerImageDesktop: a.string(),  // Desktop banner
    detailPageMainBannerImageMobile: a.string(),   // Mobile banner
    mainSubtitle01: a.string(),
    mainTitle02: a.string(),
    galleryTitle: a.string(),
    VersionPageMainTitle02: a.string(),
    VersionPageMainTitle01: a.string(),
    VersionPageGalleryTitle: a.string(),
    interiorImages: a.json(),
    exteriorImages: a.json(),
    vehcileConfiguration: a.json(),
    vehicleShowingOrderNumber: a.integer(),
    modelYear: a.string(),
    modelSeats: a.integer(),
    Seo: a.hasMany('SeoContent', 'modelId'),

    // New fields from Toyota Main API
    ToyotaMainApi_IDENTIFICADORPRODUCTO: a.string(),
    ToyotaMainApi_MODELO: a.string(),
    ToyotaMainApi_CODIGOMODELO: a.string(),
    ToyotaMainApi_VERSION: a.string(),
    ToyotaMainApi_CODIGOVERSION: a.string(),
    ToyotaMainApi_TRANSMISION: a.string(),
    ToyotaMainApi_TRACCION: a.string(),
    ToyotaMainApi_TAPICERA: a.string(),
    ToyotaMainApi_CLASE: a.string(),
    ToyotaMainApi_CARROCERIA: a.string(),
    ToyotaMainApi_MOTOR: a.string(),
    ToyotaMainApi_ANIOMODELO: a.string(),
    ToyotaMainApi_DESCRIPCION: a.string(),
    ToyotaMainApi_COMBUSTIBLE: a.string(),
    ToyotaMainApi_CILINDRAJE: a.string(),
    ToyotaMainApi_CAPACIDAD: a.string(),
    ToyotaMainApi_ACTIVO: a.boolean(),
    ToyotaMainApi_PRECIO: a.string(),
    ToyotaMainApi_VALORIVA: a.string(),
    ToyotaMainApi_VALORIMPCONSUMO: a.string(),
    ToyotaMainApi_VALORBRUTO: a.string(),
    ToyotaMainApi_DISPONIBLE: a.boolean(),
    ToyotaMainApi_GRUPOSUBLINEA: a.string(),
    ToyotaMainApi_CODIGOKATASHIKI: a.string(),
});